spring:
    datasource:
#        url: jdbc:mysql://192.168.254.86:3306/simplesys?useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true
#        username: shxt
#        password: shxtmysql
        url: jdbc:mysql://192.168.254.98:3306/test?useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true
        username: test
        password: test
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        removeAbandoned: true
        removeAbandonedTimeout: 1800
        logAbandoned: true
    http:
      encoding:
        force: true
        charset: UTF-8
        enabled: true
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

logging:
      file: D:/logs/logs.log
      level:
        root: INFO
        org:
          springframework:
                    web: INFO
server:
    port: 8088
    tomcat:
       uri-encoding: UTF-8

pagehelper:
    offset-as-page-num: true
    row-bounds-with-count: true
    reasonable: true


mybatis:
   configuration:
     map-underscore-to-camel-case: true
     call-setters-on-nulls: true



